import './globals.css'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'

import PageHeader from '@/components/PageHeader';

const jost = Jost({
  subsets: ['latin'],
  variable: '--font-jost',
});

export const metadata: Metadata = {
  title: 'Product Feedback App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
      <PageHeader />
        {children}
      </body>
    </html>
  )
}
